import type { WidgetDefinition } from './types';

export const WIDGET_CATALOG: WidgetDefinition[] = [
  {
    id: 'premium-feed',
    name: 'Premium Feed',
    description:
      'Full-experience premium content feed with rich card types, video, trending, and carousel sections.',
    status: 'active',
    category: 'feed',
    supportedViewports: ['desktop'],
    cards: [
      { cardId: 'card-1x1', label: 'Feature Card (1:1)', supportedViewports: ['desktop'] },
      { cardId: 'card-2x1', label: 'Two-Column Card (2:1)', supportedViewports: ['desktop'] },
      { cardId: 'card-3x1', label: 'Three-Column Card (3:1)', supportedViewports: ['desktop'] },
      { cardId: 'card-trending', label: 'Trending Card', supportedViewports: ['desktop'] },
      { cardId: 'card-spotlight', label: 'Video Spotlight', supportedViewports: ['desktop'] },
      { cardId: 'card-video-reel', label: 'Video Reel', supportedViewports: ['desktop'] },
      { cardId: 'card-picks-carousel', label: 'Picks Carousel', supportedViewports: ['desktop'] },
    ],
    layouts: [
      { layoutId: 'feed-section', label: 'Feed Section' },
      { layoutId: 'card-grid', label: 'Card Grid' },
      { layoutId: 'section-header', label: 'Section Header' },
      { layoutId: 'trending-grid', label: 'Trending Grid' },
    ],
    placements: ['below-article', 'homepage'],
  },
  {
    id: 'regular-feed',
    name: 'Regular Feed',
    description:
      'Standard content feed with compact, text-focused cards. Different visual style from Premium Feed.',
    status: 'placeholder',
    category: 'feed',
    supportedViewports: ['desktop'],
    cards: [],
    layouts: [],
    placements: ['below-article', 'homepage', 'section-page'],
  },
  {
    id: 'deeper-dive',
    name: 'Deeper Dive',
    description:
      'In-depth content recommendations for engaged readers. Appears after article content with editorial-quality cards.',
    status: 'placeholder',
    category: 'feed',
    supportedViewports: ['desktop'],
    cards: [],
    layouts: [],
    placements: ['below-article'],
  },
  {
    id: 'explore-more',
    name: 'Explore More',
    description:
      'Contextual content suggestions based on article topic. Compact inline widget.',
    status: 'coming-soon',
    category: 'inline',
    supportedViewports: ['desktop', 'mobile'],
    cards: [],
    layouts: [],
    placements: ['below-article', 'sidebar'],
  },
  {
    id: 'mid-article',
    name: 'Mid-Article',
    description:
      'Content recommendations inserted within article body. Non-intrusive inline placement.',
    status: 'coming-soon',
    category: 'inline',
    supportedViewports: ['desktop', 'mobile'],
    cards: [],
    layouts: [],
    placements: ['mid-article'],
  },
  {
    id: 'homepage-for-you',
    name: 'Homepage For You',
    description: 'Personalized content section for publisher homepages.',
    status: 'coming-soon',
    category: 'feed',
    supportedViewports: ['desktop', 'mobile'],
    cards: [],
    layouts: [],
    placements: ['homepage'],
  },
  {
    id: 'right-rail',
    name: 'Right Rail',
    description:
      'Sidebar content recommendations. Vertical layout optimized for narrow column placement.',
    status: 'coming-soon',
    category: 'sidebar',
    supportedViewports: ['desktop'],
    cards: [],
    layouts: [],
    placements: ['sidebar'],
  },
  {
    id: 'newsroom',
    name: 'Newsroom',
    description: 'Breaking news and trending stories widget. Real-time content updates.',
    status: 'coming-soon',
    category: 'feed',
    supportedViewports: ['desktop', 'mobile'],
    cards: [],
    layouts: [],
    placements: ['homepage', 'section-page'],
  },
];
